### ISSUE TITLE
https://cpants.cpanauthors.org/ is down - 502 bad gateway

### ISSUE THREAD

**Issue by shlomif** [cpants/www-cpants#104]
https://cpants.cpanauthors.org/ is down - 502 bad gateway - nginx error. Please look into fixing it. Thanks!

**Comment by charsbar** [comment]
Thanks for the headsup. It should be fixed now.

**Comment by shlomif** [comment]
On Sat, 11 Aug 2018 00:40:00 -0700
Kenichi Ishigaki <notifications@github.com> wrote:

> Thanks for the headsup. It should be fixed now.
> 

Thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Why I Love Perl - http://shlom.in/joy-of-perl

Sisko: Q: would it be OK if my crew brought along their phasers with them?

Q: Of course. They can also bring some photon torpedoes if they wish. None of
them will work, but I don’t mind them taking them.

Please reply to list if it's a mailing list post - http://shlom.in/reply .
