### ISSUE TITLE
Obsolete URL on no_stdin_for_prompting

### ISSUE THREAD

**Issue by openstrike** [cpants/www-cpants#105]
The [page for no_stdin_for_prompting](https://cpants.cpanauthors.org/kwalitee/no_stdin_for_prompting) currently includes a reference to http://www.perlfoundation.org/perl5/index.cgi?cpan_packaging - not a link, just text in the page. However, that URL just gives a 404 and a look at [archive.org](https://web.archive.org/web/20110701000000*/http://www.perlfoundation.org/perl5/index.cgi?cpan_packaging) suggests that it may never have had any content.

I think this URL should either be removed from the page or replaced with something close to whatever the original author intended.

**Comment by charsbar** [comment]
Thanks for the heads-up. Fixed with https://github.com/cpants/Module-CPANTS-Analyse/commit/d165d67d00562687f90a8bafb741f47384799717
