### ISSUE TITLE
Lots of "Negative repeat count does nothing" warnings on test

### ISSUE THREAD

**Issue by haukex** [cpants/www-cpants#111]
On running `prove -lwr t/` I get lots of warnings like this:
`Module::CPANTS::SiteKwalitee::Pod: Negative repeat count does nothing at .../Pod/Simple/Checker.pm line 91.`
I just got started with the code base so I'm not sure yet what the cause is.

Thanks for providing this service!

**Comment by charsbar** [comment]
You must be using Perl 5.22 or above. This is because of https://github.com/perl-pod/pod-simple/pull/90 , which is really annoying especially because Pod::Simple::Checker is in core...

**Comment by haukex** [comment]
Ah, I see, thanks (this was on 5.26)

**Comment by charsbar** [comment]
Closing as Pod::Simple with the above fix has been released. Thanks.
