### ISSUE TITLE
Add Cache-Control header for badges (for GitHub)

### ISSUE THREAD

**Issue by haukex** [cpants/www-cpants#117]
According to <https://help.github.com/articles/about-anonymized-image-urls/#an-image-that-changed-recently-is-not-updating>, it would be good to add the header `Cache-Control: no-cache` for badges, so that they are refreshed properly when fetched through GitHub's [`https://camo.githubusercontent.com/`](https://github.com/atmos/camo) service. (I think another possibility might be `Cache-Control: max-age=3600, public`.) I see that `cpants.cpanauthors.org` appears to be being served via nginx - unfortunately I don't yet have enough experience with that to suggest the change myself.

**Comment by charsbar** [comment]
Hope this helps. https://github.com/cpants/www-cpants/commit/44ee9164fede1520f4c51442656409d3be83e6ed

**Comment by haukex** [comment]
I can see the header on my end, thank you very much!
