### ISSUE TITLE
Internal Server Error on Some Modules

### ISSUE THREAD

**Issue by krschwab** [cpants/www-cpants#118]
For example:

```
$ curl -si https://cpants.cpanauthors.org/release/KSCHWAB/Algorithm-LUHN_XS-1.08 | head
HTTP/1.1 500 Internal Server Error
Server: nginx/1.10.0
Date: Tue, 25 Dec 2018 13:15:02 GMT
```
Here's another: https://cpants.cpanauthors.org/release/SKONNO/Net-UPnP-1.4.6

I wish I could offer more detail, but there doesn't seem to be a pattern I can identify as to why it's only happening for some modules.

**Comment by charsbar** [comment]
Thanks for your report. Fixed with this commit: https://github.com/cpants/www-cpants/commit/d8fa6b349faa57c0a6e22a22f7a244eb64def1ee . The both pages you kindly reported to me should be ok now.
