### ISSUE TITLE
https://cpants.cpanauthors.org/ - Next button does not work

### ISSUE THREAD

**Issue by twata1** [cpants/www-cpants#119]
Hello,

I noticed the Next button did not work.

[Step to reproduce]
1. access https://cpants.cpanauthors.org/
2. click "More..."
3. click "Next"

A little dialog box appears that shows the following message.

DataTables warning: table id=releases - Ajax error.
For more information about this error, please see
http://datatables.net/tn/7

[Environment]
Internet Explorer 11.0.9600.19236 on Windows 7 32 bit
Google Chrome 71.0.3578.98 on Windows 10 32 bit

Thnak you,

**Comment by charsbar** [comment]
Thanks for spotting. Fixed locally and the issue should be gone now.
