### ISSUE TITLE
Caching issue with badges

### ISSUE THREAD

**Issue by wollmers** [cpants/www-cpants#124]
Github displays displays the badge `kwalitee 96.77` for https://github.com/wollmers/Lingua-Stem-Cistem .

https://metacpan.org/pod/Lingua::Stem::Cistem has `kwalitee 100.00`.

On the console with

```
$ wget http://cpants.cpanauthors.org/dist/Lingua-Stem-Cistem.png
```
I get `kwalitee 100.00`.

The HTTP Response Header in Github contains:

```
Age: 827065
Strict-Transport-Security: max-age=31536000; includeSubDomains
Via: 1.1 varnish
X-Cache: HIT
```

Other badges displayed via GitHub do not have this problem.

**Comment by charsbar** [comment]
Could you clear your browser cache? It's kwalitee:100.00 for me.

**Comment by charsbar** [comment]
Sorry I misread your comment. Tentatively I added Cache-Control header locally, but it looks like I need to add some more tweaks. I'll look at it more later. Thanks.

**Comment by wollmers** [comment]
Of course I did before opening this issue.

I know that Chrome is very resistant with client caches, especially in case of CSS or JS. 

So I changed to FireFox (FF), close all tabs, clear history including caches, close FF, reopen it. Use inspect -> network, deactivate cache is checked. Reset the cookies of GitHub. Refresh. All files are fetched freshly from GitHub.

If I look into the HTTP Header of other badges delivered via GitHub, e. g.  http://badge.fury.io/pl/Lingua-Stem-Cistem, it has `Age: 1037` (~17 minutes) and not `Age: 827065` (~7 months) like the Kwalitee badge.

So I guess it's a caching issue caused by the configuration of CPANTS.

**Comment by charsbar** [comment]
It's a caching issue, but maybe of a different kind. The fundamental reason is its Last-Modified header comes from the modified time of a locally cached image file of the score, which lives under public/img/ (like ```public/img/100.00.png```. which would be much older than last analyzed time of one's distributions).
Let me give a little time to sort this out..

**Comment by wollmers** [comment]
Sounds like an interesting corner case.
