### ISSUE TITLE
Kwalitee Indicator: has_tests_in_t_dir extra

### ISSUE THREAD

**Issue by philiprbrenan** [cpants/www-cpants#126]
_This distribution contains either a file called 'test.pl' (the old test file) or is missing a directory called 't'. This indicates that it uses the old test mechanism or it has no test-suite._ 

I have both a **test.pl** file and a **t/** folder yet the presence of this useful file is raising a kwalitee issue.

`Kwalitee Indicator: has_tests_in_t_dir extra`

Please consider dropping the test for t**est.pl** if the **t/** folder is present?

Thanks!

**Comment by charsbar** [comment]
I've scanned all the ```test.pl```s found in my minicpan directory. They are mixed bags and I'm not convinced to drop the test just for you, though I may add an exceptional rule for App::Yath that creates test.pl to cover both t/ and t2/.

**Comment by philiprbrenan** [comment]
With Module::Build omitting **test.pl** produces the following message:

 ./Build dist
**WARNING: the following files are missing in your kit:
	test.pl**
Please inform the author.

This leaves users of the excellent Module Build system in an invidious position - if they omit **test.pl** Module Build complains, if they include it, kwalitee complains.  This means that Module Build users will leave **test.pl** in place as its warnings are more immediate and then be unfairly discriminated against by having their modules rated as of lower quality - when of course we know that this is not the case.   This is the deep problem with all automated quality assurance systems:- they embed the biases of their authors.

May I therefore plead that this test should be dropped for modules using Module Build ?

**Comment by charsbar** [comment]
The above warning means your MANIFEST file is stale. You need to update it when you remove (or add) some files from your distribution to archive exactly what is required.
