### ISSUE TITLE
AJAX error on Releases tab

### ISSUE THREAD

**Issue by openstrike** [cpants/www-cpants#130]
When viewing the Releases tab on a dist I consistently receive this AJAX error (as a javascript pop-up):

```DataTables warning: table id=releases - Ajax error. For more information about this error, please see http://datatables.net/tn/7```

This happens in Palemoon 28.11.0 (64-bit) and in Firefox 78.0.2 (64-bit).

Some example dists showing this behaviour: [Mutex](https://cpants.cpanauthors.org/release/MARIOROY/Mutex-1.006/releases), [CGI](https://cpants.cpanauthors.org/release/LEEJO/CGI-4.50/releases), [Moo](https://cpants.cpanauthors.org/release/HAARG/Moo-2.004000/releases), etc. I've not found one today that didn't do this.

**Comment by charsbar** [comment]
Thanks for the notice. Fixed configuration.
