### ISSUE TITLE
module Text::Unmunch has_abstract_in_pod error

### ISSUE THREAD

**Issue by swan46** [cpants/www-cpants#132]
The first line in pod is:
Text::Unmunch find all endings of a word for hunspell 
Exactly this is, what Text::Unmunch provides, not more and not less.
What kind of abstract do you miss?

**Comment by charsbar** [comment]
Hi, this "abstract in pod" metric expects the first line of the name section in a module's pod to follow a certain rule: ```(Module::Name) - (abstract)```.

Your Text::Unmunch lacks this ``` - ``` to separate the module name from the abstract part. CPANTS warns you about it.

Visit also https://metacpan.org/recent to see what's actually happening.

**Comment by charsbar** [comment]
Closing this as you have fixed the issue with Text::Unmunch 0.02. Thanks.
