### ISSUE TITLE
https://api.cpanauthors.org/v5/release/CROMEDOME/Dancer2/metadata returns error

### ISSUE THREAD

**Issue by szabgab** [cpants/www-cpants#137]
```
curl https://api.cpanauthors.org/v5/release/CROMEDOME/Dancer2/metadata
```

```
{"errors":[{"message":"Expected object - got null.","path":"\/"}],"status":200}
```

**Comment by szabgab** [comment]
Same with https://api.cpanauthors.org/v5/release/BOR/Dancer2-Plugin-Argon2/metadata

**Comment by szabgab** [comment]
There are more than 1000 distributions with similar error.

**Comment by charsbar** [comment]
This is because /v5/release endpoints require Dist-Version as their name parameter.
cf. https://cpants.cpanauthors.org/dist/Dancer2 and https://cpants.cpanauthors.org/release/CROMEDOME/Dancer2-0.400001
