### ISSUE TITLE
Server throws internal server errors frequently

### ISSUE THREAD

**Issue by andk** [cpants/www-cpants#138]
cpants.cpanauthors.org has been reported to fail for several users on IRC hashtag toolchain . They see an Internal Server Error message. I myself can see that message occasionally when I reload pages several times in a row.

All pages I have visited have the footer: `Last analyzed: 2024-01-06 00:47:10` which seems a bit old, so something seems to be stuck.

**Comment by andk** [comment]
At my visit today at https://cpants.cpanauthors.org/ I saw a fresh page with the footer: `Last analyzed: 2024-02-13 05:06:08`; that quite a few hours ahead of UTC and it means the site is in principle working.

Unfortunately, after two reloads the "Internal Server Error" came back.

**Comment by andk** [comment]
In the last few days all my visits to CPANTS were successes, no internal server error appeared anymore. Closing this ticket

**Comment by charsbar** [comment]
Thank you for your report, and I'm sorry I haven't replied. I fixed a few problems on the remote server after I came home from my conference trips and a little mess afterward, but I forgot to push the fixes here. I'm looking forward to seeing you next month.
