### ISSUE TITLE
Feature request: extra check for CPAN::Changes::Spec

### ISSUE THREAD

**Issue by ghost** [cpants/www-cpants#35]
Having a clear changelog format is a good thing. Having only one Kwalitee-like service is also a good thing.

http://changes.cpanhq.org/ is a kwalitee-inspired service that only checks if distributions follow the CPAN::Changes::Spec format. Having a Kwalitee check instead of a whole service would be better.

**Comment by charsbar** [comment]
Apparently, the site is dead now.
