### ISSUE TITLE
"Used by" count does not match list of distros.

### ISSUE THREAD

**Issue by openstrike** [cpants/www-cpants#55]
On the "Used by" tab, the summary line at the top does not (always) match the list of distros underneath. For example, on http://cpants.cpanauthors.org/dist/CGI-Lite/used_by today, the summary line says "CGI-Lite is used (required) in the following 5 distribution(s)." but then instead of listing 5 distros, it only lists one (Mobile-Wurfl).

This looks like an inconsistency to me, unless I'm missing something obvious.

Pete

**Comment by eserte** [comment]
Currently the "Used by" tab seems to be completely broken. For example http://cpants.cpanauthors.org/dist/Tk/used_by says
"Tk is used (required) in the following 0 distribution(s)."

In fact, I could not find any distribution with non-zero distributions.

**Comment by charsbar** [comment]
Sorry for the inconvenience. Regenerated databases.

**Comment by eserte** [comment]
Thanks. Now it looks better, and the original issue (count does not match list of distros) also looks like it is resolved.
