### ISSUE TITLE
Typos on the front page.

### ISSUE THREAD

**Issue by shlomif** [cpants/www-cpants#66]
The front page ( http://cpants.cpanauthors.org/ ) contains the following typos:

1. «Don't take everything here too serious!» - "serious" should be "seriously".

2. «In a future version[missing ","] it might be possible to collect metadata from various distributed testers…».

Please correct them.

**Comment by charsbar** [comment]
Thanks!

**Comment by shlomif** [comment]
@charsbar : thanks for the fix!
