### ISSUE TITLE
request for rescan of a release

### ISSUE THREAD

**Issue by karenetheridge** [cpants/www-cpants#67]
this distribution - http://cpants.cpanauthors.org/dist/MouseX-App-Cmd - is listed as having unauthorized files, but that was from a PAUSE problem that was fixed shortly after the upload. Could this distribution be rescanned to clear up the error list? thank you!

**Comment by charsbar** [comment]
Started full regeneration, which would end in a day... and apparently we need a "rescan" button on the site to flx this kind of issues :)

**Comment by charsbar** [comment]
Closing as done.
