### ISSUE TITLE
Kwalitee Badge

### ISSUE THREAD

**Issue by jandrew** [cpants/www-cpants#69]
I have appreciated the CPANTS service greatly and I would like to say that CPANTS has made my code better.  What are the chances that you would issue CPANTS badges that I could use in my README?  These would be similar to the ones available for Travis, Coveralls, and others mentioned in 
http://onionstand.blogspot.com/2015/03/how-to-add-online-code-badges-to-your.html.

**Comment by charsbar** [comment]
You might want to use http://cpants.cpanauthors.org/author/jandrew.png and/or http://cpants.cpanauthors.org/dist/Data-Walk-Extracted.png (just add .png to a url and you'll get one), and if you want a better-looking badge, the code is here :) https://github.com/cpants/www-cpants/blob/master/lib/WWW/CPANTS/StatusImage.pm

**Comment by jandrew** [comment]
That's awesome.  I didn't know that was possible.

**Comment by charsbar** [comment]
Sorry that I haven't written a doc. I'm hoping I can write one at or around the QA Hackathon in April.

**Comment by davehodg** [comment]
I'm not seeing a badge for Webservice-Tesco-API. I am for my other dists.

**Comment by charsbar** [comment]
@davehodg See http://cpants.cpanauthors.org/dist/WebService-Tesco-API.png ('S') :)

**Comment by davehodg** [comment]
I seriously thought I'd done that! Weird.

**Comment by davehodg** [comment]
Style doesn't fit the other two ;) 

https://github.com/davehodg/Webservice-Tesco-API/tree/v2_additions

**Comment by charsbar** [comment]
Tweaked the badge a little (typeface, font size, and rounded corners). Hope it looks better now (at least at the CPANTS site; don't know how to update cached images).

**Comment by jandrew** [comment]
++ for the new look.

**Comment by haukex** [comment]
See also #116: SVG badges now available! Thanks @charsbar!
