### ISSUE TITLE
duplicate META.yml in MANIFEST incorrectly reported

### ISSUE THREAD

**Issue by szabgab** [cpants/www-cpants#74]
I got a failure for Pod-Tree-1.24 

manifest_matches_dist   ["MANIFEST (204) does not match dist (203):","Missing in MANIFEST: ","Missing in Dist: META.yml"]

While the actual issue was that I had META.yml mentioned twice in MANIFEST.

**Comment by ambs** [comment]
Yep, happened same to me today with some other file.

**Comment by charsbar** [comment]
Thanks. Fixed with https://github.com/cpants/Module-CPANTS-Analyse/commit/050d57f0b854f63cd0ea121e557ee8c8aa4784a7 .
