### ISSUE TITLE
Task modules with no tests

### ISSUE THREAD

**Issue by ambs** [cpants/www-cpants#75]
Probably Task modules could be accepted without tests. Just sayin'

**Comment by charsbar** [comment]
Maybe, if CPAN clients stop comlaining when there's no tests in a (Task) distribution.

Until that, I'd rather like to see at least one test even in a Task distribution just to make sure it has a module that compiles well and gives us a correct $VERSION.

**Comment by ambs** [comment]
Sure ;)
