### ISSUE TITLE
Claims a module is a test prereq when it isn't

### ISSUE THREAD

**Issue by robrwo** [cpants/www-cpants#77]
CPANS claims that a module of mine requires Test::MinimumVersion at http://cpants.cpanauthors.org/dist/File-Rotate-Simple/errors but it doesn't.

The test script is as follows:

``` perl
#!/usr/bin/env perl

BEGIN {
  unless ($ENV{RELEASE_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for release candidate testing');
  }
}


use Test::More;

use Test::MinimumVersion;
all_minimum_version_ok('v5.8.8');
```

The BEGIN block precludes the test from trying to load Test::MinimumVersion if RELEASE_TESTING is unset. It's an author test, so it won't be used except by authors/contributors.

**Comment by charsbar** [comment]
Your distribution has both t/ and xt/ directories, and I suppose you know what they are for. Just move  t/release-minimum-version.t under xt/release/ (or wherever under xt/ ) and the error should be gone.

**Comment by robrwo** [comment]
No. The git repo has t and xt directories. The distribution just has a t
ditectory with tests added by Dist::Zilla. CPANTS is not recognizing the
skip all check.

**Comment by charsbar** [comment]
Fixed with the help of Perl::PrereqScanner::NotQuiteLite 0.95+ (cf. https://metacpan.org/dist/Perl-PrereqScanner-NotQuiteLite/changes#L97)
Thanks for your patience.
