### ISSUE TITLE
Prereq matches use including core modules

### ISSUE THREAD

**Issue by pjfl** [cpants/www-cpants#80]
Since the recent changes the prereq_matches_use test has started failing for core modules.
See Unexpected. It now fails because of an undeclared dependency on parent (core Perl
module since 5.10.1) and version (core Perl module since 5.9.0). The minimum Perl version
for this module is correctly declared as 5.10.1

**Comment by pjfl** [comment]
Seems fixed

**Comment by charsbar** [comment]
Thanks for the report. Fixed locally before I squash everything.

https://github.com/cpants/www-cpants/blob/master/lib/WWW/CPANTS/Bin/Task/Analyze/UpdateRequiresAndUses.pm#L74
