### ISSUE TITLE
Prereq matches use ignoring recommends

### ISSUE THREAD

**Issue by pjfl** [cpants/www-cpants#81]
Since the recent changes the prereq_matches_use test has started ignoring the
prereq recommends metadata. See IPC-SRLock. Recommends allows a distribution
to declare optional prereqs

**Comment by pjfl** [comment]
Another use for the recommends prereq

**Comment by pjfl** [comment]
Another use for the recommends prereq is to overcome circular dependencies. See Class::Usul
and Data::Validation

**Comment by pjfl** [comment]
Seems fixed

**Comment by charsbar** [comment]
Thanks for the report. Fixed locally before I squash everything.

https://github.com/cpants/www-cpants/blob/master/lib/WWW/CPANTS/Bin/Task/Analyze/UpdateRequiresAndUses.pm#L81
