### ISSUE TITLE
Metadata: directory appears twice in dirs_array

### ISSUE THREAD

**Issue by dolmen** [cpants/www-cpants#83]
From http://cpants.cpanauthors.org/release/DOLMEN/cpan-outdated-0.31/metadata
In the `dirs_array` object, the `xt` directory appears twice.

**Comment by charsbar** [comment]
Thanks for the report. There seems something wrong in File::Find::Object, which reports the last entry twice if depth is set to true. I'll look at it further when I have some time. For now maybe I should add %seen to Module::CPANTS::Kwalitee::Files to remove duplicates.
(I also have a plan to switch it to Path::Tiny for speed and simplicity, but not now.)

**Comment by charsbar** [comment]
This has been worked around.
