### ISSUE TITLE
Indicates `extracts_nicely` violation but doesn't say how comes

### ISSUE THREAD

**Issue by andk** [cpants/www-cpants#84]
On http://cpants.cpanauthors.org/release/ANDK/CPAN-2.14-TRIAL I get `extracts_nicely` today but as far as I can see the release does extract nicely according to the description on http://cpants.cpanauthors.org/kwalitee/extracts_nicely.

``` text
% tar tzf CPAN-2.14-TRIAL.tar.gz|sed -e 's|/.*||'|uniq -c
    654 CPAN-2.14-TRIAL
```

How can I find out in which respect exactly the distro fails?

**Comment by charsbar** [comment]
That was a bug in CPANTS. Fixed and started regenerating databases. Also added an error message to show which directory CPANTS analyzer expected. Thanks.
