### ISSUE TITLE
distname_info() returns AnyData as a distname of AnyData2

### ISSUE THREAD

**Issue by charsbar** [cpants/www-cpants#85]
http://cpants.cpanauthors.org/dist/AnyData2 shows a page on the latest version of AnyData, instead of the one of AnyData2. http://cpants.cpanauthors.org/release/REHSACK/AnyData2-0.002 works fine.

Basically, it is an issue of distname_info(), which derives from CPAN::DistnameInfo (and a patch in its GH repository).

**Comment by rehsack** [comment]
Can I do anything to help fixing the issue?

**Comment by charsbar** [comment]
@rehsack, as for your issue, the above commit should work. I'll look into this further when I have more time, to let distname_info() parse AnyData2 and the likes correctly (ie. not to consider the last "2" as a version number, but this assumption may not be true especially in older distributions, so I'd rather research more extensively first).

**Comment by dolmen** [comment]
This seems to be fixed.
