### ISSUE TITLE
"valid_signature" should be true if the signature is valid even if not trusted

### ISSUE THREAD

**Issue by rivy** [cpants/www-cpants#87]
I'm receiving this error for my module uploads:

```
valid_signature
    WARNING: This key is not certified with a trusted signature! Primary key fingerprint: ...
```

But, the signature is actually correct / valid for the distribution, although the key used is unknown / not trusted by the system.

As it stands, the message, as written, and under the "Error" category, seems confusing. It initially made me think that I had signed the module incorrectly. But that's not the case. The module was correctly signed; the signature is just not trusted on CPANTS. And, as I know of no mechanism to push a trusted signature to CPANTS, I think this should be removed as an error.

My thought is that as long as the enclosed signature matches the module (which proves  that the module is unaltered) that the signature should be seen as valid, even if the provenience of the signature itself is unknown (aka, untrusted).

I not planning on removing the signature from my modules because I believe the signature has usefulness for module verification. But the current CPANTS setup shows that correct usage as an error. And, this is just going to encourage devs to upload without signatures at all. 

Thoughts?

**Comment by charsbar** [comment]
As the following example shows, CPANTS doesn't say your module has a valid_signature issue, and this can be confirmed in the Metadata tab (look inside the "kwalitee" block, not at "valid_signature" on the top. The latter stores a raw return value from Module::Signature, i.e. whose 0 means SIGNATURE_OK, -1 means SIGNATURE_MISSING etc).

http://cpants.cpanauthors.org/release/RIVY/Win32-CommandLine-0.938
http://cpants.cpanauthors.org/release/RIVY/Win32-CommandLine-0.938/metadata

However, I understand your concerns about the said warning messages from Module::Signature being listed in the "Error" tab. I'll look into code/databases to see if I can safely cut them without removing other useful information.

**Comment by rivy** [comment]
Thanks for the quick response.

I see the "kwalitee" metric is 100 and the metadata block shows no issues. The message listed in the "Error" tab just misleads me into thinking there is a problem.

I appreciate that you're taking the time to look at it.

**Comment by charsbar** [comment]
I hope https://github.com/cpants/Module-CPANTS-SiteKwalitee/commit/46bb183a41c08015e110415e84c7815dbde8c94b should fix this issue. Let's see when the databases are all regenerated.

**Comment by charsbar** [comment]
Looks fine. Closed with a test. Thanks.

**Comment by rivy** [comment]
Looks good here. Thanks.
