### ISSUE TITLE
/kwalitee/no_pax_headers shows distribution names incorrectly

### ISSUE THREAD

**Issue by dolmen** [cpants/www-cpants#88]
The following distributions are incorrectly listed on the [/kwalitee/no_pax_header](http://cpants.cpanauthors.org/kwalitee/no_pax_headers) page: the version appear, but not the distribution name. The link to the release page is also incorrect.
- [ELCAMLOST/ClickHouse-0.01](http://cpants.cpanauthors.org/release/ELCAMLOST/ClickHouse-0.01) shown as "0.01" instead of "ClickHouse-0.01"
- [PHLUKS/Unwire-1.0](http://cpants.cpanauthors.org/release/PHLUKS/Unwire-1.0) shown as "v-1.0" instead of "Unwire-1.0"
- [ALLEN/String-DiffLine-0.03](http://cpants.cpanauthors.org/release/ALLEN/String-DiffLine-0.03) shown as "0.03"

Some distributions in this list are also shown multiple times. For example ALLEN/String-DiffLine-0.03 is shown both as "0.03" and as "String-DiffLine-0.03".

**Comment by charsbar** [comment]
Thanks for the heads-up. I'm hoping it's due to the full database regeneration I've started a few hours ago, but I'll look into it later again.

**Comment by dolmen** [comment]
Similar issue on [/kwalitee/has_readme](http://cpants.cpanauthors.org/kwalitee/has_readme) for [AUTOLIFE/Mojo-UserAgent_t2.tar.gz](http://cpants.cpanauthors.org/release/AUTOLIFE/Mojo-UserAgent_t2) (which is a very broken tarball).

As cpants has to deal with many weired tarballs that do no not make valid CPAN distribution I think it would be safer to NOT try to split the tarball file name into *$distname*-*$version*.tar.gz and instead just use the file name without the compress extension.

**Comment by charsbar** [comment]
It turns out that there are 0.01.tar.gz / v-1.0.tar.gz / 0.03.tar.gz in their backpan directories. We have something to fix here, but your proposal not to split the tarball doesn't help.

**Comment by charsbar** [comment]
It looks like this issue has already been fixed.
