### ISSUE TITLE
No new dists/releases in almost 3 weeks

### ISSUE THREAD

**Issue by openstrike** [cpants/www-cpants#95]
At time of writing, the most recent dists listed on the [homepage](https://cpants.cpanauthors.org/) are from 13/05/2017 which is almost 3 weeks ago.

When looking at a recent release on CPAN such as [DateTime 1.43](https://metacpan.org/release/DROLSKY/DateTime-1.43) from 3 days ago, it has no [entry at CPANTS](https://cpants.cpanauthors.org/release/DROLSKY/DateTime-1.43) and all we see is the 404. It appears that something is amiss with the feed of new releases.

**Comment by charsbar** [comment]
Thanks for the heads-up. I forgot to enable some of the cron jobs I disabled during the Perl Toolchain Summit. I enabled them. Everything should be ready in a few hours I hope.
