### ISSUE TITLE
Badge is not displayed at GitHub

### ISSUE THREAD

**Issue by choroba** [cpants/www-cpants#96]
For example, I can see the badge alone at https://cpants.cpanauthors.org/dist/Syntax-Construct.png , but it isn't displayed in the README.md file at [Syntax::Construct](/choroba/syntactic-construct) on GitHub.

**Comment by choroba** [comment]
See also https://www.reddit.com/r/perl/comments/6g0xwd/perl_shieldsbadges/ where a similar problem was resolved for https://badge.fury.io

**Comment by charsbar** [comment]
Thanks for the heads-up. It turned out I kind of misconfigured ssl_certificate in the nginx configuration. It had pointed to cert.pem, which worked for web browsers, but apparently not for camo (image proxy for GH). I modified it to point to fullchain.pem, and it seems working now.
