### ISSUE TITLE
SpamcupNG fails Kwalitee due "main_module_version_matches_dist_version"

### ISSUE THREAD

**Issue by glasswalk3r** [cpants/www-cpants#97]
SpamcupNG fails the core test "main_module_version_matches_dist_version", but the distribution version indeed matches the main module (there is only one actually) version, as you can see in the attached screenshot.
As far as I could check, all files that mention version (Meta*, dist.ini, Makefile.PL) also mentions "1.0" as the version, so I'm not sure if I missing something, or there is an error with Kwalitee reports.
![2018-03-12 11_24_03-cpants](https://user-images.githubusercontent.com/3854915/37289336-365b9d42-25e8-11e8-99ec-66e94b564f04.png)

**Comment by charsbar** [comment]
This is because the case of the first letter of your distribution (**s**pamcupNG) doesn't match the one of the module (**S**pamcupNG), thus CPANTS (correctly) fails to find the "main module" of your distribution. Since a few years ago, PAUSE (and CPANTS) has been stricter about the case of names. Certainly there's a room to improve this error message.

**Comment by glasswalk3r** [comment]
Got it. I'm considering renaming the distribution to App::SpamcupNG, so that should be fixed as well, so probably you will want to close this issue too.

**Comment by glasswalk3r** [comment]
@charsbar , where exactly this error message could be improved? I already checked CPANTS and this project itself, but couldn't find the error or the sub name.

**Comment by charsbar** [comment]
@glasswalk3r https://github.com/cpants/Module-CPANTS-SiteKwalitee/blob/master/lib/Module/CPANTS/SiteKwalitee/Version.pm#L99-L133

Patches are always welcome.

**Comment by glasswalk3r** [comment]
Done! See https://github.com/cpants/Module-CPANTS-SiteKwalitee/pull/6

**Comment by glasswalk3r** [comment]
Done! See https://github.com/cpants/Module-CPANTS-SiteKwalitee/pull/6

**Comment by glasswalk3r** [comment]
Done!

**Comment by charsbar** [comment]
Thanks! Updated the site.
